<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>smartneedle_interface</name>
  <version>0.1.0</version>
  <description>Lightweight ROS 2 to OpenIGTLink bridge for streaming reconstructed needle shapes to 3D Slicer.</description>
  <maintainer email="maribernardes@gmail.com">Mariana Bernardes</maintainer>
  <license>TODO: License declaration</license>

  <depend>ament_index_python</depend>
  <depend>geometry_msgs</depend>
  <depend>python3-numpy</depend>
  <depend>python3-scipy</depend>
  <depend>rclpy</depend>
  <depend>ros2_igtl_bridge</depend>

  <exec_depend>fbg_shape_pipeline_cpp</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
