tcp_receiver_node:
  ros__parameters:
    tcp_host: "127.0.0.1"
    tcp_port: 50012
    reconnect_ms: 1000
    output_topic: "/needle/fbg_frame"
    compact_output_topic: ""

curvature_processor_node:
  ros__parameters:
    input_topic: "/needle/fbg_frame"
    output_topic: "/needle/state/curvatures"
    shape_output_topic: "/needle/state/current_shape"
    shape_frame_id: "needle"
    enable_data_averaging: false
    data_average_window: 1
    enable_temporal_averaging: false
    temporal_average_window: 1
